In [1]:
import pandas as pd
import zipfile
import os
import numpy as np

If you add a shortcut to the SIADS 696 folder to your drive, you should be able to read the folders in.

In [2]:
#from google.colab import drive
#drive.mount('/content/gdrive')

In [3]:
# Path where datasets are saved
#data_path = '/content/gdrive/MyDrive/SIADS_696_Milestone_II/Datasets/EIA_files'
data_path = os.getcwd()

# Read SEDS production data (rename state column to match consumption data)
file_prod = os.path.join(data_path, 'Prod_dataset.xlsx')
df_prod = pd.read_excel(file_prod, sheet_name='Data').rename(columns={"StateCode": "State"})

# Read SEDS consumption data
file_cons = os.path.join(data_path, 'use_all_btu.xlsx')
df_cons = pd.read_excel(file_cons, sheet_name='Data')

# Read hand picked categories of data
file_cat = os.path.join(data_path, 'SEDS_categories.xlsx')
df_cat = pd.read_excel(file_cat)

# Printing
display(df_prod)
display(df_cons)
display(df_cat.head())

,Data_Status,State,MSN,1960,1961,1962,1963,1964,1965,1966,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,2024F,AK,B1PRB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000
1,2024F,AK,B1PRP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000
2,2024F,AK,BDFDB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,21.000,27.000,29.000,15.000,0.000,0.000,0.00,0.000,0.000,0.000
3,2024F,AK,BDPRP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.000,5.000,5.000,3.000,0.000,0.000,0.00,0.000,0.000,0.000
4,2024F,AK,BFPRB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,21.000,27.000,29.000,15.000,0.000,0.000,0.00,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2138,2024F,X3,TEPRB,530978.0,674013.0,918907.0,1147416.0,1321824.0,1568087.0,2059270.0,...,4601323.000,4692834.000,4731871.000,4788614.000,5108039.000,4387986.000,4456374.00,4484698.000,4734499.000,4520104.000
2139,2024F,X5,COPRK,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.717,5.722,5.723,5.706,5.698,5.691,5.69,5.684,5.689,5.689
2140,2024F,X5,PAPRB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,65465.000,35156.000,32701.000,27811.000,25350.000,26002.000,22714.00,15244.000,17175.000,21749.000
2141,2024F,X5,PAPRP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,11451.000,6144.000,5714.000,4874.000,4449.000,4569.000,3992.00,2682.000,3019.000,3823.000
2142,2024F,X5,TEPRB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,65465.000,35156.000,32701.000,27811.000,25350.000,26002.000,22714.00,15244.000,17175.000,21749.000

,Data_Status,State,MSN,1960,1961,1962,1963,1964,1965,1966,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,2024F,AK,ABICB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-3.0,-3.0,-2.0,-14.0,-10.0,-7.0,-8.0,-6.0,-6.0,-10.0
1,2024F,AK,ARICB,312.0,555.0,489.0,589.0,791.0,878.0,1646.0,...,12450.0,12365.0,13561.0,4804.0,11973.0,12391.0,13425.0,12981.0,13173.0,13322.0
2,2024F,AK,ARTCB,312.0,555.0,489.0,589.0,791.0,878.0,1646.0,...,12450.0,12365.0,13561.0,4804.0,11973.0,12391.0,13425.0,12981.0,13173.0,13322.0
3,2024F,AK,ARTXB,312.0,555.0,489.0,589.0,791.0,878.0,1646.0,...,12450.0,12365.0,13561.0,4804.0,11973.0,12391.0,13425.0,12981.0,13173.0,13322.0
4,2024F,AK,AVACB,5209.0,6441.0,5202.0,3273.0,2319.0,1478.0,1086.0,...,1308.0,1240.0,1239.0,1264.0,1245.0,915.0,1037.0,1073.0,1019.0,1096.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16695,2024F,WY,WYTXB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16696,2024F,WY,WZEIB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16697,2024F,WY,WZTCB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16698,2024F,WY,ZWCDP,254.0,266.0,141.0,294.0,228.0,140.0,276.0,...,285.0,311.0,292.0,280.0,246.0,356.0,413.0,393.0,256.0,359.0
16699,2024F,WY,ZWHDP,8655.0,8724.0,8528.0,8174.0,9133.0,8816.0,8592.0,...,7583.0,7678.0,7895.0,8177.0,8906.0,8069.0,7865.0,8441.0,8339.0,7573.0

,Category 0,Category 1,Category 2,Category 3,MSN Code,Description,Unit
0,Production,Fossil Fuels,Petroleum,Petroleum,PAPRB,Crude oil production (including lease condensate),Billion Btu
1,Consumption,Fossil Fuels,Petroleum,Petroleum,PAACB,All petroleum products consumed by the transpo...,Billion Btu
2,Consumption,Fossil Fuels,Petroleum,Petroleum,PACCB,All petroleum products consumed by the commerc...,Billion Btu
3,Consumption,Fossil Fuels,Petroleum,Petroleum,PAEIB,All petroleum products consumed by the electri...,Billion Btu
4,Consumption,Fossil Fuels,Petroleum,Petroleum,PAICB,All petroleum products consumed by the industr...,Billion Btu

In [4]:
# Combine prod/cons datasets
df = pd.concat([df_prod, df_cons], ignore_index=True)
df

,Data_Status,State,MSN,1960,1961,1962,1963,1964,1965,1966,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,2024F,AK,B1PRB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2024F,AK,B1PRP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2024F,AK,BDFDB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,21.0,27.0,29.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2024F,AK,BDPRP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,5.0,5.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2024F,AK,BFPRB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,21.0,27.0,29.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18838,2024F,WY,WYTXB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18839,2024F,WY,WZEIB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18840,2024F,WY,WZTCB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18841,2024F,WY,ZWCDP,254.0,266.0,141.0,294.0,228.0,140.0,276.0,...,285.0,311.0,292.0,280.0,246.0,356.0,413.0,393.0,256.0,359.0
18842,2024F,WY,ZWHDP,8655.0,8724.0,8528.0,8174.0,9133.0,8816.0,8592.0,...,7583.0,7678.0,7895.0,8177.0,8906.0,8069.0,7865.0,8441.0,8339.0,7573.0

In [5]:
# Filter for MSN codes, drop Data_Status, and remove non-states
df_filtered = df[df['MSN'].isin(df_cat['MSN Code'])].drop(columns=['Data_Status'])
df_filtered = df_filtered[~df_filtered['State'].isin(['US', 'X3', 'X5'])]
df_filtered

,State,MSN,1960,1961,1962,1963,1964,1965,1966,1967,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,AK,B1PRB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,AK,BDFDB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,21.0,27.0,29.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0
8,AK,CLPRB,11263.0,11497.0,13588.0,13307.0,11622.0,13931.0,14461.0,14430.0,...,17747.0,13942.0,14365.0,13752.0,14867.0,15523.0,15838.0,15451.0,15496.0,15118.0
12,AK,EMFDB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,AK,GEPRB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,186.0,186.0,186.0,186.0,186.0,186.0,186.0,186.0,186.0,186.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18827,WY,WWEIB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18828,WY,WWICB,378.0,327.0,344.0,378.0,344.0,516.0,516.0,430.0,...,115.0,115.0,88.0,87.0,87.0,87.0,87.0,133.0,133.0,133.0
18833,WY,WYCCB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18834,WY,WYEGB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,12818.0,14976.0,14742.0,13843.0,14204.0,18809.0,28824.0,33370.0,29468.0,30714.0
18836,WY,WYICB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
# Check some stats for dirty data (all are clean)
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2703 entries, 0 to 18836
Data columns (total 67 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   State   2703 non-null   object
 1   MSN     2703 non-null   object
 2   1960    2703 non-null   float64
 3   1961    2703 non-null   float64
 4   1962    2703 non-null   float64
 5   1963    2703 non-null   float64
 6   1964    2703 non-null   float64
 7   1965    2703 non-null   float64
 8   1966    2703 non-null   float64
 9   1967    2703 non-null   float64
 10  1968    2703 non-null   float64
 11  1969    2703 non-null   float64
 12  1970    2703 non-null   float64
 13  1971    2703 non-null   float64
 14  1972    2703 non-null   float64
 15  1973    2703 non-null   float64
 16  1974    2703 non-null   float64
 17  1975    2703 non-null   float64
 18  1976    2703 non-null   float64
 19  1977    2703 non-null   float64
 20  1978    2703 non-null   float64
 21  1979    2703 non-null   float64
 22  1980    2703 non-null   float64
 23  1981    2703 non-null   float64
 24  1982    2703 non-null   float64
 25  1983    2703 non-null   float64
 26  1984    2703 non-null   float64
 27  1985    2703 non-null   float64
 28  1986    2703 non-null   float64
 29  1987    2703 non-null   float64
 30  1988    2703 non-null   float64
 31  1989    2703 non-null   float64
 32  1990    2703 non-null   float64
 33  1991    2703 non-null   float64
 34  1992    2703 non-null   float64
 35  1993    2703 non-null   float64
 36  1994    2703 non-null   float64
 37  1995    2703 non-null   float64
 38  1996    2703 non-null   float64
 39  1997    2703 non-null   float64
 40  1998    2703 non-null   float64
 41  1999    2703 non-null   float64
 42  2000    2703 non-null   float64
 43  2001    2703 non-null   float64
 44  2002    2703 non-null   float64
 45  2003    2703 non-null   float64
 46  2004    2703 non-null   float64
 47  2005    2703 non-null   float64
 48  2006    2703 non-null   float64
 49  2007    2703 non-null   float64
 50  2008    2703 non-null   float64
 51  2009    2703 non-null   float64
 52  2010    2703 non-null   float64
 53  2011    2703 non-null   float64
 54  2012    2703 non-null   float64
 55  2013    2703 non-null   float64
 56  2014    2703 non-null   float64
 57  2015    2703 non-null   float64
 58  2016    2703 non-null   float64
 59  2017    2703 non-null   float64
 60  2018    2703 non-null   float64
 61  2019    2703 non-null   float64
 62  2020    2703 non-null   float64
 63  2021    2703 non-null   float64
 64  2022    2703 non-null   float64
 65  2023    2703 non-null   float64
 66  2024    2703 non-null   float64
dtypes: float64(65), object(2)
memory usage: 1.4+ MB

In [7]:
# Transpose Years/MSN, but keep State and filter for year range (optional)
id_vars = ['State', 'MSN']
value_vars = [col for col in df_filtered.columns if col not in id_vars]
df_filtered_melted = df_filtered.melt(id_vars=id_vars, value_vars=value_vars, var_name='Year', value_name='Value')
df_filtered_transposed = df_filtered_melted.pivot_table(index=['State', 'Year'], columns='MSN', values='Value')
df_filtered_transposed = df_filtered_transposed.reset_index()
#df_filtered_transposed = df_filtered_transposed[df_filtered_transposed['Year'].isin(range(1980, 2025))]
df_filtered_transposed

MSN,State,Year,B1ACB,B1PRB,BDACB,BDCCB,BDEIB,BDFDB,BDRCB,CLACB,...,SOPRB,SORCB,WWCCB,WWEIB,WWICB,WWPRB,WYCCB,WYEGB,WYICB,WYPRB
0,AK,1960,0.0,0.0,0.0,0.0,0.0,0.0,0.0,86.0,...,0.0,0.0,34.0,0.0,1840.0,3681.0,0.0,0.0,0.0,0.0
1,AK,1961,0.0,0.0,0.0,0.0,0.0,0.0,0.0,42.0,...,0.0,0.0,35.0,0.0,2288.0,4145.0,0.0,0.0,0.0,0.0
2,AK,1962,0.0,0.0,0.0,0.0,0.0,0.0,0.0,43.0,...,0.0,0.0,32.0,0.0,2511.0,4246.0,0.0,0.0,0.0,0.0
3,AK,1963,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36.0,...,0.0,0.0,31.0,0.0,2700.0,4383.0,0.0,0.0,0.0,0.0
4,AK,1964,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33.0,...,0.0,0.0,32.0,0.0,2993.0,4728.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3310,WY,2020,0.0,11356.0,826.0,0.0,0.0,0.0,0.0,0.0,...,610.0,37.0,253.0,0.0,87.0,1612.0,0.0,18809.0,0.0,18809.0
3311,WY,2021,0.0,12574.0,488.0,0.0,0.0,0.0,0.0,0.0,...,674.0,52.0,253.0,0.0,87.0,1656.0,0.0,28824.0,0.0,28824.0
3312,WY,2022,0.0,18241.0,313.0,0.0,0.0,0.0,0.0,0.0,...,715.0,68.0,253.0,0.0,133.0,2043.0,0.0,33370.0,0.0,33370.0
3313,WY,2023,0.0,20454.0,363.0,0.0,0.0,0.0,0.0,0.0,...,692.0,87.0,253.0,0.0,133.0,1794.0,0.0,29468.0,0.0,29468.0
3314,WY,2024,0.0,19313.0,138.0,0.0,0.0,0.0,0.0,0.0,...,1557.0,99.0,253.0,0.0,133.0,1706.0,0.0,30714.0,0.0,30714.0

In [8]:
# Show some stats
display(df_filtered_transposed.sample(10))
display(df_filtered_transposed.describe())

MSN,State,Year,B1ACB,B1PRB,BDACB,BDCCB,BDEIB,BDFDB,BDRCB,CLACB,...,SOPRB,SORCB,WWCCB,WWEIB,WWICB,WWPRB,WYCCB,WYEGB,WYICB,WYPRB
1938,NE,2013,0.0,0.0,2515.0,0.0,0.0,0.0,0.0,0.0,...,31.0,30.0,537.0,619.0,474.0,4568.0,0.0,6148.0,0.0,6148.0
3240,WV,2015,0.0,0.0,1255.0,0.0,0.0,0.0,0.0,0.0,...,67.0,62.0,1275.0,66.0,1130.0,11988.0,0.0,4696.0,0.0,4696.0
1025,IN,2010,0.0,0.0,981.0,0.0,0.0,4560.0,0.0,0.0,...,131.0,131.0,6313.0,3202.0,11431.0,33942.0,7.0,10004.0,0.0,10011.0
1128,KY,1983,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,435.0,0.0,11229.0,30858.0,0.0,0.0,0.0,0.0
2591,RI,2016,0.0,0.0,302.0,188.0,0.0,130.0,935.0,0.0,...,192.0,89.0,216.0,2021.0,135.0,3769.0,23.0,67.0,0.0,91.0
765,HI,2010,0.0,0.0,102.0,0.0,40.0,0.0,0.0,0.0,...,1928.0,1801.0,2945.0,40.0,4392.0,7744.0,0.0,891.0,0.0,891.0
2439,OR,1994,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,462.0,462.0,1345.0,6031.0,27774.0,45054.0,0.0,0.0,0.0,0.0
566,DE,2006,0.0,0.0,43.0,0.0,0.0,0.0,0.0,0.0,...,8.0,2.0,88.0,5.0,29.0,646.0,0.0,0.0,0.0,0.0
1846,ND,1986,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,82.0,0.0,139.0,3002.0,0.0,0.0,0.0,0.0
100,AL,1995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,150.0,150.0,1650.0,20558.0,187712.0,221956.0,0.0,0.0,0.0,0.0

MSN,Year,B1ACB,B1PRB,BDACB,BDCCB,BDEIB,BDFDB,BDRCB,CLACB,CLCCB,...,SOPRB,SORCB,WWCCB,WWEIB,WWICB,WWPRB,WYCCB,WYEGB,WYICB,WYPRB
count,3315.000000,3315.000000,3315.000000,3315.000000,3315.000000,3315.000000,3315.000000,3315.000000,3315.000000,3315.000000,...,3315.000000,3315.000000,3315.000000,3315.000000,3315.000000,3315.000000,3315.000000,3315.000000,3315.000000,3315.000000
mean,1992.000000,532.407541,416.246154,917.412368,6.871493,2.733937,918.911011,22.733032,68.404223,2487.257014,...,2178.498341,932.644947,1349.081448,4605.007843,28716.892006,45616.519759,1.858824,4381.391554,1.108296,4384.358974
std,18.764493,11105.879116,5055.926594,3015.018162,90.844368,41.852275,3849.278703,259.759414,458.995586,6031.015416,...,12590.559711,4725.085946,2299.237504,11032.960536,36193.426814,46878.944630,12.122115,21331.967884,13.926656,21340.802962
min,1960.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,-35.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,-1.000000
25%,1976.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,...,0.000000,0.000000,160.000000,0.000000,1872.000000,7340.000000,0.000000,0.000000,0.000000,0.000000
50%,1992.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,324.000000,...,6.000000,5.000000,443.000000,17.000000,15714.000000,30821.000000,0.000000,0.000000,0.000000,0.000000
75%,2008.000000,0.000000,0.000000,235.500000,0.000000,0.000000,0.000000,0.000000,0.000000,2659.500000,...,262.000000,202.000000,1501.000000,2920.000000,43179.000000,69678.500000,0.000000,35.000000,0.000000,35.000000
max,2024.000000,426607.000000,137029.000000,37012.000000,2194.000000,900.000000,47215.000000,4668.000000,14588.000000,89986.000000,...,291454.000000,93033.000000,18732.000000,82057.000000,244662.000000,255738.000000,184.000000,423924.000000,344.000000,424035.000000

In [9]:
# Save df to CSV
output_file_path = os.path.join(data_path, 'df_seds_cleaned.csv')
df_filtered_transposed.to_csv(output_file_path, index=False)